config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  mount_uploader :image, ImageUploader, :mount_on => :image


  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_future

  def review_average
    if reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size
    else
      return '0'
    end
  end
  scope :by_search, -> (query) { where('title LIKE ? OR director LIKE ?', "%#{query}%", "%#{query}%") }
  scope :by_duration, -> (limit1, limit2) { where('runtime_in_minutes BETWEEN ? AND ?', limit1,limit2) }


  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  
  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_secure_password
  after_destroy :delete_reviews

  def delete_reviews
    reviews.destroy_all
  end

  def full_name
    "#{firstname.capitalize} #{lastname.capitalize}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 
before_action :authorize

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      
      redirect_to admin_users_path, notice: "The user #{@user.firstname} was created with success!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path(@user)
    else
      render :edit
    end 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.delete_notify(@user).deliver
    redirect_to admin_users_path
  end

  protected
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :admin)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user && current_user.admin
      flash[:error] = 'You have to be an admin to access this page.'
      redirect_to :root
    end
    
  end

  helper_method :current_user, :authorize

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.where(nil).page(params[:page]).per(5)
    @movies = @movies.by_search(params[:query]) if params[:query].present?
    case params[:duration]
    when 'Under 90 minutes'
      limit1 = 0
      limit2 = 89
    when 'Between 90 and 120 min'
      limit1 = 90
      limit2 = 120
    when 'Over 120 min'
      limit1 = 121
      limit2 = 9999
    else
      limit1 = 0
      limit2 = 9999   
    end
    @movies = @movies.by_duration(limit1, limit2) if params[:duration].present?
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])  
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      redirect_to movies_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id]) 
  end

  protected
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
    
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "admin", "Admin?" %>
    <%= f.check_box :admin  %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin User Management</h1>
<%= paginate @users %>
  <div class="media">
    <div class="media-body">
      <table class="table table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><button type="button" class="btn btn-primary"><%= link_to "Edit", edit_admin_user_path(user) %></td>
              <td></button><button type="button" class="btn btn-danger"><%= link_to "Delete", admin_user_path(user), data: {:confirm => "You sure?"}, method: :delete %></button></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <button type="button" class="btn btn-primary"><%= link_to "Add new user", new_admin_user_path %></button>
    </div>
  </div>

app/views/admin/users/new.html.erb
<h1>Add user</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if current_user.admin? %>
      <p>You are an admin, you can now access the <%= link_to "Admin page", admin_users_path %> </p>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container"> 
    <a class="navbar-brand">Rotten Mangoes</a>
      <button class="navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Submit a movie!", new_movie_path, class: "a" %></li> 
        <%= form_tag movies_path, class: "navbar-form navbar-left", :method => 'get' do %>
            <div><%= text_field_tag :query, params[:query], placeholder: 'Movie title or director' %></div>
            <%= select_tag :duration, options_for_select([['Filter by duration'],['Under 90 minutes'],['Between 90 and 120 min'],['Over 120 min']]) %>
            <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
        <% end %>   
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>

<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
<% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "upload a poster" %><br>
    <%= f.file_field :image %>
  </div>
  <p>
  <div>
    <%= f.label "poster_image_url" %><br>
    <%= f.text_field "poster_image_url" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <%= image_tag movie.image_url(:thumb) if movie.image? %>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p><br/>
  <p>Review:<%= movie.review_average %>/10</p>
  <hr>

<% end %>

app/views/movies/_movies.html.erb
<%= paginate @movies %>
<% @movies.each do |movie| %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <div><%= link_to image_tag(movie.poster_image_url), movie_path(movie) %></div>
  <div><%= image_tag movie.image_url(:thumb) if movie.image? %></div>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Director: <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p><br/>
  <p>Review:<%= movie.review_average %>/10</p>
  <hr>

<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<%= render 'movies' %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<%= image_tag @movie.image_url %>
<h2><%= @movie.title %> (<%= link_to "Edit", edit_movie_path(@movie) %>, <%= link_to "Delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
  <p><%= review.text %></p>
  <p><%= review.rating_out_of_ten %>/10</p>
  <small>Author: <%= link_to "#{review.user.full_name}", user_path(review.user) %> on <%= review.created_at.to_date %></small><br/>
<% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<h1>My Profile</h1>
<h2><%= @user.full_name %> </h2>
<h3><%= @user.email %></h3>
<hr>

<h3>Reviews of <%= @user.firstname.capitalize %></h3>
<% @user.reviews.each do |review| %>
<div>
<p> Review: <%= review.text %></p>
</div>
<% end %>